### ISSUE TITLE
Comrade Seongho Lim, what is this again?

### ISSUE THREAD

**Issue by Kim-Sub** [seongholim-11/nomadcoder_react#1]
Comrade Seongho Lim, what is this again?
Are you a true coding nomad?
Where is the source of your coding skills?
let me know that too

![](https://starecat.com/content/wp-content/uploads/my-code-doesnt-work-i-have-no-idea-why-my-code-works.jpg)

**Comment by seongholim-11** [comment]
It's my top secret code
please give a money to get my code
